"""Generate platform adapters from tokens.json. Standard Python only."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parent

def generate():
    t=json.loads((ROOT/'tokens.json').read_text())
    color=t['color']; spacing=t['space']; radius=t['radius']; typography=t['typography']
    css=['/* Generated by build_tokens.py; edit tokens.json and regenerate. */', ':root {']
    for key,val in color.items(): css.append(f'  --cs-{key}: {val};')
    for group,values in [('space',spacing),('radius',radius)]:
        for key,val in values.items(): css.append(f'  --cs-{group}-{key}: {val/16:g}rem;')
    for key,v in typography['styles'].items():
        css.extend([f'  --cs-type-{key}-size: {v["size"]/16:g}rem;',f'  --cs-type-{key}-line: {v["lineHeight"]};',f'  --cs-type-{key}-tracking: {v["tracking"]/16:g}rem;'])
    css.extend(['  --cs-font-sans: Arial, Helvetica, sans-serif;', '  --cs-font-mono: "Courier New", monospace;',f'  --cs-control-height: {t["size"]["controlWeb"]/16:g}rem;',f'  --cs-motion-fast: {t["motion"]["fast"]}ms;',f'  --cs-motion-panel: {t["motion"]["panel"]}ms;','}'])
    (ROOT/'web').mkdir(exist_ok=True)
    (ROOT/'web/theme.css').write_text('\n'.join(css)+'\n')
    (ROOT/'mobile').mkdir(exist_ok=True)
    ts='// Generated. Logical layout units; native system font; allow text scaling.\n'
    ts+='export const colors = '+json.dumps(color,indent=2)+' as const;\n'
    for name,obj in [('spacing',spacing),('radii',radius),('sizes',t['size'])]:ts+='export const '+name+' = '+json.dumps(obj,indent=2)+' as const;\n'
    styles={k:{'fontSize':v['size'],'lineHeight':round(v['size']*v['lineHeight'],2),'letterSpacing':v['tracking'],'fontWeight':str(v['weight'])} for k,v in typography['styles'].items()}
    ts+='export const typeStyles = '+json.dumps(styles,indent=2)+' as const;\n'
    ts+='export const buttonStyles = { minHeight: sizes.controlMobile, borderRadius: radii.control, paddingHorizontal: spacing["16"], backgroundColor: colors.action, justifyContent: "center", alignItems: "center" } as const;\n'
    (ROOT/'mobile/theme.ts').write_text(ts)
    camel=lambda s:s.split('-')[0]+''.join(x.title() for x in s.split('-')[1:])
    dart=["// Generated tokens and a light theme adapter. See mobile/README.md.","import 'package:flutter/material.dart';",'', 'abstract final class CallstormColors {']
    for k,v in color.items():dart.append(f'  static const {camel(k)} = Color(0xFF{v[1:].upper()});')
    dart.extend(['}','', 'abstract final class CallstormSpace {'])
    for k,v in spacing.items():dart.append(f'  static const s{k} = {float(v)};')
    dart.extend(['}','', 'abstract final class CallstormRadius {'])
    for k,v in radius.items():dart.append(f'  static const {camel(k)} = {float(v)};')
    dart.extend(['}','', 'abstract final class CallstormType {'])
    for k,v in typography['styles'].items():dart.append(f'  static const {camel(k)} = TextStyle(fontSize: {float(v["size"])}, height: {v["lineHeight"]}, letterSpacing: {float(v["tracking"])}, fontWeight: FontWeight.w{v["weight"]});')
    dart.extend(['}','', '''ThemeData callstormTheme() {
  const c = CallstormColors;
  final scheme = ColorScheme.fromSeed(
    seedColor: CallstormColors.olive,
    brightness: Brightness.light,
  ).copyWith(
    primary: CallstormColors.action,
    onPrimary: CallstormColors.onAction,
    secondary: CallstormColors.lavender,
    onSecondary: CallstormColors.ink,
    surface: CallstormColors.surface,
    onSurface: CallstormColors.ink,
    error: CallstormColors.dangerText,
    onError: CallstormColors.onAction,
    outline: CallstormColors.borderStrong,
  );
  return ThemeData(
    useMaterial3: true,
    colorScheme: scheme,
    scaffoldBackgroundColor: CallstormColors.canvas,
    dividerColor: CallstormColors.border,
    textTheme: const TextTheme(
      headlineLarge: CallstormType.page,
      headlineMedium: CallstormType.insight,
      titleLarge: CallstormType.section,
      titleMedium: CallstormType.card,
      bodyLarge: CallstormType.body,
      bodyMedium: CallstormType.label,
      labelSmall: CallstormType.caption,
    ).apply(bodyColor: CallstormColors.ink, displayColor: CallstormColors.ink),
    appBarTheme: const AppBarTheme(
      backgroundColor: CallstormColors.canvas,
      foregroundColor: CallstormColors.ink,
      elevation: 0,
      scrolledUnderElevation: 0,
    ),
    filledButtonTheme: FilledButtonThemeData(
      style: FilledButton.styleFrom(
        minimumSize: const Size(48, 48),
        backgroundColor: CallstormColors.action,
        foregroundColor: CallstormColors.onAction,
        elevation: 0,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(CallstormRadius.control)),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        textStyle: CallstormType.label,
      ),
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        minimumSize: const Size(48, 48),
        foregroundColor: CallstormColors.ink,
        side: const BorderSide(color: CallstormColors.borderStrong),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(CallstormRadius.control)),
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: CallstormColors.surface,
      contentPadding: const EdgeInsets.all(16),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(CallstormRadius.control)),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(CallstormRadius.control),
        borderSide: const BorderSide(color: CallstormColors.borderStrong),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(CallstormRadius.control),
        borderSide: const BorderSide(color: CallstormColors.focus, width: 2),
      ),
    ),
  );
}
'''.replace('  const c = CallstormColors;\n','')])
    (ROOT/'mobile/callstorm_theme.dart').write_text('\n'.join(dart))

if __name__=='__main__':generate()
