'use strict';
const $=id=>document.getElementById(id);
const loads=[1,5,10,20,40,80];
const runs=[{id:128,version:'2.4',date:'Sep 13, 2026',success:94.2,cost:.084,latency:[.55,.59,.63,.78,1.18,2.2],quality:[97.6,96.4,94.4,88.4],stage:[.012,.043,.024128],baseline:127},{id:127,version:'2.3',date:'Sep 12, 2026',success:91.8,cost:.096,latency:[.5,.53,.59,.7,1,1.94],quality:[96.4,94.8,91.6,84.4],stage:[.014,.049,.025128],baseline:126},{id:126,version:'2.2',date:'Sep 11, 2026',success:90.6,cost:.102,latency:[.58,.61,.69,.9,1.3,2.4],quality:[96,93.6,91.2,81.6],stage:[.015,.052,.025412],baseline:125},{id:125,version:'2.1',date:'Sep 10, 2026',success:89.4,cost:.108,latency:[.6,.66,.75,.98,1.41,2.6],quality:[95.2,92.4,90.4,79.6],stage:[.016,.055,.025552],baseline:124},{id:124,version:'2.0',date:'Sep 9, 2026',success:88.2,cost:.114,latency:[.63,.7,.81,1.04,1.56,2.8],quality:[94.4,91.6,88.8,78],stage:[.017,.059,.024548],baseline:123},{id:123,version:'1.9',date:'Sep 8, 2026',success:87.2,cost:.12,latency:[.65,.72,.85,1.08,1.64,2.9],quality:[94,90.4,87.2,77.2],stage:[.018,.063,.02364],baseline:122},{id:122,version:'1.8',date:'Sep 7, 2026',success:86.4,cost:.127,latency:[.68,.77,.92,1.15,1.72,3],quality:[93.6,90,86,76],stage:[.019,.067,.023728],baseline:121},{id:121,version:'1.7',date:'Sep 6, 2026',success:85.2,cost:.135,latency:[.7,.82,.99,1.22,1.85,3.15],quality:[92.8,89.2,84.8,74],stage:[.02,.072,.02302],baseline:null}];
const names=['Standard refund','Escalation','Noisy caller','Interrupted refund'];
let state={tab:'load',run:128,point:4,scenario:3,baseline:true};
const current=()=>runs.find(r=>r.id===state.run);
const previous=()=>runs.find(r=>r.id===current().baseline);
const money=n=>'$'+n.toFixed(3);
const set=(id,text)=>$(id).textContent=text;
function changeTab(tab){state.tab=tab;render();}
function render(){const r=current(),b=previous();const cap=loads[r.latency.findLastIndex(v=>v<=1)];
set('versionLabel','Version '+r.version);set('runLabel',(r.id===128?'Latest evaluation':'Evaluation')+' · #'+r.id);set('runMeta',r.date+' · 1,000 quality calls + 600 load calls');
$('capacityStat').innerHTML=cap+' <small>calls</small>';$('qualityStat').innerHTML=r.success.toFixed(1)+'<small>%</small>';set('costStat',money(r.cost));
set('qualityDelta',b?'↗ '+(r.success-b.success).toFixed(1)+' pp':'First run');set('costDelta',b?'↘ '+((1-r.cost/b.cost)*100).toFixed(1)+'%':'First run');
$('qualityDelta').parentNode.lastChild.textContent=b?' vs previous run':' · no comparison';$('costDelta').parentNode.lastChild.textContent=b?' vs previous run':' · no comparison';
set('summaryTitle',r.id===128?'A stronger agent. A clear load limit.':'Your agent, at this point in time.');set('summaryPill','2 checks need attention');
for(const el of document.querySelectorAll('[role=tab]')){const active=el.dataset.tab===state.tab;el.setAttribute('aria-selected',String(active));el.tabIndex=active?0:-1;}
$('insightPanel').setAttribute('aria-labelledby','tab-'+state.tab);$('baseline').disabled=!b;$('baseline').checked=state.baseline&&!!b;
if(state.tab==='load')renderLoad();else if(state.tab==='quality')renderQuality();else renderCost();}
function shellSvg(inner,label){return '<svg viewBox="0 0 640 254" role="img" aria-label="'+label+'">'+inner+'</svg>';}
function renderLoad(){const r=current(),b=previous();const max=Math.max(2.5,Math.ceil(Math.max(...r.latency,...(b?b.latency:[]))*2)/2);const x=i=>55+i*109;const y=v=>207-v/max*164;const cap=loads[r.latency.findLastIndex(v=>v<=1)],first=r.latency.findIndex(v=>v>1);
set('chartQuestion','How much traffic can this agent handle?');set('chartSubtitle','P95 response time · seconds · Lower is better');
let svg='';for(let i=0;i<=5;i++){let v=max*i/5;svg+='<line x1="55" y1="'+y(v)+'" x2="600" y2="'+y(v)+'" stroke="#edeee7"/><text x="40" y="'+(y(v)+4)+'" text-anchor="end" fill="#94998b" font-size="12">'+v.toFixed(1)+'</text>';}
svg+='<rect x="'+x(first)+'" y="40" width="'+(614-x(first))+'" height="167" fill="#faead5" opacity=".6"/>';
svg+='<line x1="55" y1="'+y(1)+'" x2="600" y2="'+y(1)+'" stroke="#b89567" stroke-dasharray="4 5"/><text x="61" y="'+(y(1)-9)+'" fill="#a1845d" font-size="11">1.0 s budget</text>';
if(state.baseline&&b)svg+='<polyline points="'+b.latency.map((v,i)=>x(i)+','+y(v)).join(' ')+'" fill="none" stroke="#ccb5d5" stroke-width="2" stroke-dasharray="5 5"/>';
svg+='<path d="M55 207 L'+r.latency.map((v,i)=>x(i)+' '+y(v)).join(' L')+' L600 207 Z" fill="#c6dcfa" opacity=".23"/><polyline points="'+r.latency.map((v,i)=>x(i)+','+y(v)).join(' ')+'" fill="none" stroke="#8faed6" stroke-width="3" stroke-linejoin="round"/>';
svg+='<line x1="'+x(state.point)+'" y1="32" x2="'+x(state.point)+'" y2="207" stroke="#b4bba5" stroke-dasharray="3 5"/>';
r.latency.forEach((v,i)=>{svg+='<circle class="point" data-point="'+i+'" cx="'+x(i)+'" cy="'+y(v)+'" r="'+(i===state.point?6:4)+'" fill="'+(i===state.point?'#fff':'#8faed6')+'" stroke="'+(i===state.point?'#758c50':'#8faed6')+'" stroke-width="2"><title>'+loads[i]+' concurrent calls: '+v.toFixed(2)+' seconds P95</title></circle><text x="'+x(i)+'" y="229" text-anchor="middle" fill="#909786" font-size="12">'+loads[i]+'</text>';});
const lx=Math.min(544,Math.max(91,x(state.point)));svg+='<rect x="'+(lx-38)+'" y="7" width="76" height="26" rx="5" fill="#e8eddc"/><text x="'+lx+'" y="24" text-anchor="middle" fill="#53683b" font-size="12">'+r.latency[state.point].toFixed(2)+' s</text><text x="328" y="252" text-anchor="middle" fill="#989d90" font-size="11">Concurrent calls</text>';
$('chart').innerHTML=shellSvg(svg,'P95 response time exceeds the 1 second budget at '+loads[first]+' concurrent calls.')+'<div class="cost-legend"><span><i style="background:#8faed6"></i>Current run</span>'+(state.baseline&&b?'<span><i style="background:#ccb5d5"></i>Previous run</span>':'')+'<span><i style="background:#f7d1a8"></i>Above budget</span></div>';
if(!$('loadRange')) $('chartControls').innerHTML='<div class="range-control"><label for="loadRange">Inspect load <strong></strong></label><input id="loadRange" aria-label="Concurrent call load" type="range" min="0" max="5" step="1"></div>';
$('loadRange').value=state.point;$('loadRange').setAttribute('aria-valuetext',loads[state.point]+' concurrent calls');document.querySelector('label[for="loadRange"] strong').textContent=loads[state.point]+' calls';
$('loadRange').oninput=e=>{state.point=Number(e.target.value);renderLoad();};
$('chart').querySelectorAll('[data-point]').forEach(el=>el.onclick=()=>{state.point=Number(el.dataset.point);renderLoad();});
set('takeawayTitle','Stay at '+cap+' concurrent calls.');set('takeawayBody','That is the highest tested load within your response-time budget. The first breach appears at '+loads[first]+' calls.');
const value=r.latency[state.point],over=value>1;$('observation').innerHTML='<small>AT '+loads[state.point]+' CONCURRENT CALLS</small><strong>'+value.toFixed(2)+' s <small>P95 response</small></strong><small>'+(over?Math.round((value-1)*100)+'% over the 1.0 s budget':Math.round((1-value)*100)+'% below the 1.0 s budget')+'</small>';
$('observation').style.background=over?'#f3e7d8':'#e7edda';set('nextStep','Inspect the slow responses before increasing traffic.');set('chartFootnote','600 synthetic calls · 100 per load level');set('evidenceButton','Inspect '+loads[state.point]+'-call evidence ↗');}
function renderQuality(){const r=current(),b=previous();set('chartQuestion','Where does the agent lose the task?');set('chartSubtitle','Task success by scenario · Higher is better');
$('chart').innerHTML='<div class="axis-caption"><span>Scenario</span><span>Success rate · target ≥95%</span></div>'+names.map((n,i)=>'<button class="scenario" data-scenario="'+i+'" aria-pressed="'+(state.scenario===i)+'"><span class="scenario-name">'+n+'</span><span class="scenario-track"><span class="scenario-fill" style="width:'+r.quality[i]+'%"></span><span style="position:absolute;left:95%;top:0;height:100%;border-left:1px dashed #9b936d"></span>'+(state.baseline&&b?'<span title="Previous: '+b.quality[i]+'%" style="position:absolute;left:'+b.quality[i]+'%;top:0;height:100%;border-left:2px solid #ac8bb6"></span>':'')+'</span><strong>'+r.quality[i].toFixed(1)+'%</strong></button>').join('')+'<div class="cost-legend"><span><i style="background:#c6dcfa"></i>Current run</span>'+(state.baseline&&b?'<span><i style="background:#ac8bb6"></i>Previous run marker</span>':'')+'</div>';
$('chart').querySelectorAll('[data-scenario]').forEach(el=>el.onclick=()=>{state.scenario=Number(el.dataset.scenario);renderQuality();});
$('chartControls').innerHTML='<div class="scenario-detail">Select a scenario to see its result and review the evidence.</div>';
const i=state.scenario,failed=Math.round(250*(1-r.quality[i]/100));set('takeawayTitle','Interruptions need the most work.');set('takeawayBody','Interrupted refunds have the lowest success rate: '+r.quality[3].toFixed(1)+'%. Start here to improve overall quality.');
$('observation').style.background='#f3e7d8';$('observation').innerHTML='<small>'+names[i].toUpperCase()+'</small><strong>'+failed+' of 250 calls failed</strong><small>'+r.quality[i].toFixed(1)+'% success'+(b?' · '+(r.quality[i]-b.quality[i]).toFixed(1)+' pp vs previous':'')+'</small>';
set('nextStep',i===3?'Review whether the agent stops speaking and preserves the caller’s intent.':'Review the failed examples to understand where this scenario breaks.');set('chartFootnote','1,000 calls · 250 per scenario · Same test suite');set('evidenceButton','Review '+names[i].toLowerCase()+' ↗');}
function renderCost(){const r=current(),b=previous();set('chartQuestion','Is each successful call costing less?');set('chartSubtitle','Agent API cost / successful call · USD · Lower is better');const selected=runs.filter(v=>v.id<=r.id).slice(0,5).reverse();const max=.15,x=i=>75+i*(500/Math.max(selected.length-1,1)),y=v=>205-v/max*161;let svg='';for(let v=0;v<=.15001;v+=.05)svg+='<line x1="55" x2="600" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#edeee7"/><text x="42" y="'+(y(v)+4)+'" text-anchor="end" fill="#94998b" font-size="12">$'+v.toFixed(2)+'</text>';
svg+='<polyline fill="none" stroke="#829b52" stroke-width="3" points="'+selected.map((v,i)=>x(i)+','+y(v.cost)).join(' ')+'"/>';
selected.forEach((v,i)=>{svg+='<circle cx="'+x(i)+'" cy="'+y(v.cost)+'" r="5" fill="#fff" stroke="#829b52" stroke-width="2"/><text x="'+x(i)+'" y="'+(y(v.cost)-14)+'" text-anchor="middle" fill="#677749" font-size="12">'+money(v.cost)+'</text><text x="'+x(i)+'" y="230" text-anchor="middle" fill="#909786" font-size="12">v'+v.version+'</text>';});
if(state.baseline&&b)svg+='<line x1="55" x2="600" y1="'+y(b.cost)+'" y2="'+y(b.cost)+'" stroke="#bba4c6" stroke-dasharray="5 5"/>';
$('chart').innerHTML=shellSvg(svg,'Cost per successful call decreases across releases to '+money(r.cost))+'<div class="cost-legend"><span><i style="background:#829b52"></i>Cost / successful call</span>'+(state.baseline&&b?'<span><i style="background:#bba4c6"></i>Previous run cost</span>':'')+'</div>';
$('chartControls').innerHTML='<div class="range-control"><span>Total agent API cost <strong>$'+(r.cost*r.success*10).toFixed(2)+'</strong></span><span>'+Math.round(r.success*10)+' successful calls</span></div>';
set('takeawayTitle',b?'Less cost. More successful calls.':'Your first cost baseline.');set('takeawayBody',b?'Cost per success is down '+((1-r.cost/b.cost)*100).toFixed(1)+'% from '+money(b.cost)+'. The same 1,000-call suite also completes more tasks.':'Use this run as the starting point for comparing future releases.');
$('observation').style.background='#e7edda';$('observation').innerHTML='<small>PER 1,000 SUCCESSFUL CALLS</small><strong>'+(b?'$'+((b.cost-r.cost)*1000).toFixed(2)+' lower API cost':'$'+(r.cost*1000).toFixed(2)+' estimated API cost')+'</strong><small>Normalized comparison · same call mix</small>';
set('nextStep','Check which API stage drives the spend before changing the agent.');set('chartFootnote','Quality suite only · Includes API spend on failed calls');set('evidenceButton','Explore cost breakdown ↗');}
function openDrawer(title,html){$('drawerEyebrow').textContent=title;$('drawerContent').innerHTML=html;if(!$('drawer').open)$('drawer').showModal();$('drawer').scrollTop=0;}
function evidence(){const r=current();if(state.tab==='load'){const p=r.latency[state.point],n=loads[state.point];const total=Math.round(p*1000),end=Math.round(total*.19),speech=Math.round(total*.22),model=total-end-speech;
openDrawer('LOAD EVIDENCE · RUN #'+r.id,'<h2>What happens at '+n+' calls?</h2><p>P95 response time is '+p.toFixed(2)+' seconds at this load. '+(p>1?'This exceeds':'This meets')+' the 1.0-second budget.</p><span class="evidence-label">100 synthetic calls · '+n+' concurrent</span><div class="evidence-block"><h3>One representative slow turn</h3><p>This sample turn took '+total+' ms. Stage durations describe this turn, not summed percentiles.</p><div class="trace-bar"><span style="width:19%;background:#c6dcfa"></span><span style="width:59%;background:#dbc5e2"></span><span style="width:22%;background:#f7d1a8"></span></div><div class="timing-row"><span>Endpointing</span><strong>'+end+' ms</strong></div><div class="timing-row"><span>Model + tool wait</span><strong>'+model+' ms</strong></div><div class="timing-row"><span>Speech generation</span><strong>'+speech+' ms</strong></div><div class="timing-row"><span>Total response</span><strong>'+total+' ms</strong></div></div><div class="transcript"><span class="eyebrow">SAMPLE CONVERSATION</span><div class="utterance"><small>CALLER · 00:18.000</small>Can you check whether my refund has been processed?</div><div class="utterance agent"><small>AGENT · '+(18+p).toFixed(3)+' s</small>Your refund has been approved. It should reach your original payment method within five business days.</div></div><details><summary>What to investigate</summary><p>Compare endpointing, model and tool wait, and speech timing across slow turns. A load correlation alone does not establish the root cause.</p></details>');
}else if(state.tab==='quality'){const i=state.scenario;const examples=[['I returned the item yesterday. When will I get the money back?','Your refund has been submitted.','No refund tool was called. The agent claimed an action without evidence.'],['I need to speak to a person about this rejected refund.','You should contact our support team.','The required transfer tool was not called; the caller was left without a handoff.'],['My order number is 4192.','I found order 4193 and will refund it.','The agent used the wrong order identifier without confirming it.'],['Actually, I only want to refund one item, not the whole order.','As I was saying, I will process the full refund for you.','The agent continued over the interruption and failed to adopt the corrected scope.']][i];
openDrawer('CONVERSATION EVIDENCE · RUN #'+r.id,'<h2>'+names[i]+'</h2><p>'+r.quality[i].toFixed(1)+'% success across 250 synthetic calls. This is an illustrative failed example.</p><span class="evidence-label">Failed · Task completion</span><div class="transcript"><div class="utterance"><small>CALLER · 00:18</small>'+examples[0]+'</div><div class="utterance agent"><small>AGENT · 00:19</small>'+examples[1]+'</div></div><div class="evidence-block"><h3>Why this failed</h3><p>'+examples[2]+'</p></div><details><summary>Evaluation criteria</summary><p>Pass requires the correct requested outcome, supported by tool events, with no contradictory action. The transcript and event trace must support the verdict. In this demo, verdicts and evidence are synthetic.</p></details>');
}else{const total=r.cost*r.success*10;
openDrawer('COST EVIDENCE · RUN #'+r.id,'<h2>Where the API spend goes.</h2><p>All API spend from the quality suite, including failed calls, divided by '+Math.round(r.success*10)+' successful outcomes.</p><div class="evidence-block"><h3>1,000 evaluated calls</h3>'+['Speech recognition','Model inference','Speech generation'].map((name,i)=>'<div class="timing-row"><span>'+name+'</span><strong>$'+(r.stage[i]*1000).toFixed(2)+'</strong></div>').join('')+'<div class="timing-row"><span>Total agent API spend</span><strong>$'+total.toFixed(2)+'</strong></div><div class="timing-row"><span>Cost / successful call</span><strong>'+money(r.cost)+'</strong></div></div><p>Excludes telephony, hosting, test generation, and evaluation-model costs. This is agent API efficiency, not the total cost of operating the system.</p>');}}
function openRuns(){const r=current();$('runList').innerHTML=runs.map(v=>'<button class="run-row '+(v.id===r.id?'selected':'')+'" data-run="'+v.id+'"><span>Evaluation #'+v.id+' · Refund assistant v'+v.version+'<small>'+v.date+' · '+v.success.toFixed(1)+'% task success</small></span><span>'+(v.id===r.id?'✓ Selected':'Open ↗')+'</span></button>').join('');$('runDialog').showModal();$('runList').querySelectorAll('[data-run]').forEach(e=>e.onclick=()=>{state.run=Number(e.dataset.run);$('runDialog').close();render();});}
function methodology(){openDrawer('METRIC DEFINITIONS','<h2>What these numbers mean.</h2><dl class="metric-def"><dt>P95 response time</dt><dd>Time from the caller finishing speech to the first audible agent response. 95% of measured responses are at or below this value. Load steps contain 100 calls each.</dd><dt>Validated concurrency</dt><dd>The highest tested number of simultaneous calls with P95 response time at or below 1.0 second. This is a latency check, not a guarantee of production readiness.</dd><dt>Task success</dt><dd>Successful outcomes divided by evaluated calls. Each scenario has 250 calls; the quality suite has 1,000. The release target is at least 95%.</dd><dt>Cost per successful call</dt><dd>Total agent API cost across successful and failed quality-suite calls, divided by successful outcomes. Load-sweep, evaluator, infrastructure, and telephony costs are excluded.</dd><dt>Previous run</dt><dd>The immediately preceding saved evaluation uses the same synthetic scenario mix and load levels. Differences are descriptive; no statistical significance is claimed.</dd><dt>Demo evidence</dt><dd>All metrics, traces, and conversations in this dashboard are illustrative. No live agent is connected.</dd></dl>');}
$('allFindings').onclick=()=>{const r=current(),first=r.latency.findIndex(v=>v>1);openDrawer('FINDINGS · RUN #'+r.id,'<h2>Two things to look at next.</h2><p>Start with the evidence behind each missed target.</p><button class="finding-row" id="findingLoad"><strong>Response time crosses the budget at '+loads[first]+' calls ↗</strong><small>'+r.latency[first].toFixed(2)+' s P95 · 1.0 s target</small></button><button class="finding-row" id="findingQuality"><strong>Interrupted refunds underperform ↗</strong><small>'+r.quality[3].toFixed(1)+'% success · 95% target</small></button>');$('findingLoad').onclick=()=>{state.tab='load';state.point=first;render();evidence();};$('findingQuality').onclick=()=>{state.tab='quality';state.scenario=3;render();evidence();};};
$('baseline').onchange=e=>{state.baseline=e.target.checked;render();};document.querySelectorAll('[data-tab]').forEach(el=>{el.onclick=()=>changeTab(el.dataset.tab);el.onkeydown=e=>{const tabs=['load','quality','cost'];let i=tabs.indexOf(state.tab);if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();i=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;changeTab(tabs[i]);$('tab-'+tabs[i]).focus();};});
$('evidenceButton').onclick=evidence;$('methodButton').onclick=methodology;['historyButton','runPicker','runsNav'].forEach(id=>$(id).onclick=openRuns);$('overviewNav').onclick=()=>{changeTab('load');window.scrollTo({top:0,behavior:'smooth'});};document.querySelector('.brand').onclick=e=>{e.preventDefault();changeTab('load');window.scrollTo({top:0,behavior:'smooth'});};$('closeDrawer').onclick=()=>$('drawer').close();$('closeRuns').onclick=()=>$('runDialog').close();for(const id of ['drawer','runDialog'])$(id).addEventListener('click',e=>{if(e.target===$(id)){const b=$(id).getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$(id).close();}});
render();

if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tool={name:'explore_evaluation',title:'Explore an evaluation',description:'Select a saved demo run and an evaluation dimension in the visible dashboard. Optionally inspect a tested concurrency level.',inputSchema:{type:'object',properties:{run_id:{type:'integer',enum:runs.map(r=>r.id)},dimension:{type:'string',enum:['load','quality','cost']},concurrent_calls:{type:'integer',enum:loads}},required:['run_id','dimension'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['run_id','dimension','concurrent_calls'].includes(k))||!runs.some(r=>r.id===input.run_id)||!['load','quality','cost'].includes(input.dimension)||('concurrent_calls' in input&&!loads.includes(input.concurrent_calls)))throw new Error('Choose a valid run, dimension, and tested concurrency.');state.run=input.run_id;state.tab=input.dimension;if('concurrent_calls' in input)state.point=loads.indexOf(input.concurrent_calls);render();const r=current();return{run_id:r.id,dimension:state.tab,task_success_percent:r.success,cost_per_successful_call_usd:r.cost,selected_concurrency:loads[state.point],p95_response_seconds:r.latency[state.point],data:'illustrative'};}};
 try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
