'use strict';
const DATA=JSON.parse(document.getElementById('systemData').textContent);
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let all=false, active='overview', toastTimer;
function notify(text){$('toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',2500);}
async function copyText(text){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);}else{const el=document.createElement('textarea');el.value=text;el.style.cssText='position:fixed;left:-9999px;top:0';document.body.append(el);el.select();const copied=document.execCommand('copy');el.remove();if(!copied)throw new Error('Copy unavailable');}notify('Copied to clipboard.');}catch{notify('Clipboard unavailable. Use the download button or select the text.');}}
function download(name){const text=DATA.resources[name];if(typeof text!=='string'){notify('Resource unavailable.');return;}const mime=name.endsWith('.json')?'application/json':name.endsWith('.css')?'text/css':'text/plain';const url=URL.createObjectURL(new Blob([text],{type:mime+';charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name.split('/').pop();document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);notify('Download prepared: '+name.split('/').pop());}
function selectSection(id,scroll=true){if(!DATA.sections.some(s=>s.id===id))id='overview';active=id;document.querySelectorAll('.board').forEach(s=>s.hidden=!all&&s.id!==id);document.querySelectorAll('.nav-link').forEach(a=>{const selected=a.dataset.section===id;a.classList.toggle('active',selected);if(selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('currentSection').textContent=all?'Complete system · all sections':DATA.sections.find(s=>s.id===id).title;if(scroll){if(all)$(id).scrollIntoView({behavior:'auto',block:'start'});else window.scrollTo({top:0,behavior:'auto'});}if(id==='desktop'||all)loadDesktop();}
function loadDesktop(){const frame=$('desktopFrame');if(!frame.srcdoc)frame.srcdoc=DATA.desktop;}
document.querySelectorAll('[data-section]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();history.replaceState(null,'','#'+a.dataset.section);selectSection(a.dataset.section);}));
document.querySelector('.gallery-brand').onclick=e=>{e.preventDefault();selectSection('overview');history.replaceState(null,'','#overview');};
$('viewAll').onclick=()=>{all=!all;document.body.classList.toggle('view-all',all);$('viewAll').setAttribute('aria-pressed',String(all));$('viewAll').textContent=all?'Browse one section':'View all sections';selectSection(active);};
$('desktopFrame').addEventListener('load',()=>{$('desktopFrame').dataset.ready='true';});
$('printSystem').onclick=()=>{if($('desktopFrame').dataset.ready==='true'){window.print();return;}$('desktopFrame').addEventListener('load',()=>window.print(),{once:true});loadDesktop();};
window.addEventListener('hashchange',()=>selectSection(location.hash.slice(1)));
$('coverage').innerHTML=DATA.sections.slice(1).map((s,i)=>'<a class="coverage-item" href="#'+s.id+'" data-cover="'+s.id+'"><span class="cs-eyebrow">'+String(i+2).padStart(2,'0')+' / '+esc(s.group)+'</span><h3>'+esc(s.title)+' ↗</h3><p>'+({color:'All core colors and semantic roles.',pastels:'Core families and eight optional extensions.',type:'Nine styles, with complete text examples.',space:'Spacing, corners, depth, and dimensions.',controls:'Buttons, fields, choices, and navigation.',patterns:'Summaries, evidence, overlays, and states.',charts:'Question-led analytical specimens.',desktop:'The full original interactive dashboard.',mobile:'Overview and evidence screen prototypes.',access:'Motion, focus, contrast, and behavior.',tokens:'Search, inspect, copy, and download.'}[s.id])+'</p></a>').join('');
document.querySelectorAll('[data-cover]').forEach(a=>a.onclick=e=>{e.preventDefault();selectSection(a.dataset.cover);history.replaceState(null,'','#'+a.dataset.cover);});
document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyText(b.dataset.copy));
document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>notify(b.dataset.toast));
document.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>download(b.dataset.download));
document.querySelectorAll('[data-copy-resource]').forEach(b=>b.onclick=()=>copyText(DATA.resources[b.dataset.copyResource]));
document.querySelectorAll('[data-overlay]').forEach(b=>b.onclick=()=>$(b.dataset.overlay==='drawer'?'exampleDrawer':'exampleDialog').showModal());
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('loadingButton').onclick=()=>{const b=$('loadingButton');b.disabled=true;b.setAttribute('aria-busy','true');b.textContent='Loading…';setTimeout(()=>{b.disabled=false;b.removeAttribute('aria-busy');b.textContent='Try loading';notify('Example operation completed.');},1200);};
$('demoForm').onsubmit=e=>{e.preventDefault();const input=$('workspaceName');if(!input.value.trim()){input.setAttribute('aria-invalid','true');$('workspaceError').textContent='Enter a workspace name to continue.';$('workspaceError').hidden=false;$('formMessage').textContent='';input.focus();return;}input.removeAttribute('aria-invalid');$('workspaceError').hidden=true;$('formMessage').textContent='Example saved: '+input.value.trim()+'. No server data was changed.';};
document.querySelectorAll('.switch').forEach(b=>b.onclick=()=>b.setAttribute('aria-checked',b.getAttribute('aria-checked')==='true'?'false':'true'));
$('budgetRange').oninput=e=>$('budgetValue').textContent=(Number(e.target.value)/10).toFixed(1)+' s';
$('readingSize').oninput=e=>{$('readingSample').style.fontSize=e.target.value+'px';$('readingSizeValue').textContent=e.target.value+' px';};
document.querySelectorAll('.sample-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.sample-nav button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('sampleNavStatus').textContent=b.textContent+' selected';});
function keyboardTabs(selector,onSelect){const tabs=[...document.querySelectorAll(selector)];tabs.forEach((b,i)=>{const choose=()=>{tabs.forEach(x=>{const selected=x===b;x.setAttribute('aria-selected',String(selected));x.tabIndex=selected?0:-1;});onSelect(b);};b.onclick=choose;b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;tabs[n].click();tabs[n].focus();};});}
keyboardTabs('.local-tab',b=>{$('localTabContent').textContent=b.dataset.local+' content selected.';});
document.querySelectorAll('[data-list-row]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-list-row]').forEach(x=>x.classList.toggle('selected',x===b));$('selectedRowStatus').textContent=b.childNodes[0].textContent.trim()+' selected.';});
for(const id of ['retryExample','refreshExample'])$(id).onclick=()=>{const b=$(id);b.disabled=true;b.textContent='Refreshing…';setTimeout(()=>{b.disabled=false;b.textContent=id==='retryExample'?'Try again':'Refresh example';notify('Example refreshed successfully.');},900);};
$('playMotion').onclick=()=>$('motionTrack').classList.toggle('playing');
const loads=[1,5,10,20,40,80],values=[.55,.59,.63,.78,1.18,2.2],base=[.5,.53,.59,.7,1,1.94];
function renderChart(i){const x=n=>58+n*112,y=n=>225-n/2.5*180;let svg='';for(let n=0;n<=2.5;n+=.5)svg+='<line x1="58" x2="618" y1="'+y(n)+'" y2="'+y(n)+'" stroke="#e4e4db"/><text x="44" y="'+(y(n)+4)+'" text-anchor="end">'+n.toFixed(1)+'</text>';svg+='<rect x="506" y="40" width="112" height="185" fill="#fae9d7" opacity=".7"/><line x1="58" x2="618" y1="'+y(1)+'" y2="'+y(1)+'" stroke="#897047" stroke-dasharray="5 5"/><text x="62" y="'+(y(1)-9)+'">1.0 s budget</text><polyline points="'+base.map((v,n)=>x(n)+','+y(v)).join(' ')+'" fill="none" stroke="#8a6698" stroke-width="2" stroke-dasharray="6 5"/><polyline points="'+values.map((v,n)=>x(n)+','+y(v)).join(' ')+'" fill="none" stroke="#607da2" stroke-width="3"/>';
values.forEach((v,n)=>{svg+='<circle cx="'+x(n)+'" cy="'+y(v)+'" r="'+(n===i?7:4)+'" fill="'+(n===i?'#e2eccb':'#fff')+'" stroke="'+(n===i?'#343e29':'#607da2')+'" stroke-width="2"/><text x="'+x(n)+'" y="251" text-anchor="middle">'+loads[n]+'</text>';});svg+='<text x="340" y="280" text-anchor="middle">Concurrent calls · tested levels</text><text x="58" y="21">P95 response time (s)</text>';$('loadPlot').innerHTML=svg;$('chartLoadValue').textContent=loads[i]+' calls';$('chartLoad').setAttribute('aria-valuetext',loads[i]+' concurrent calls, '+values[i].toFixed(2)+' seconds');$('chartAnswer').textContent='At '+loads[i]+' calls, P95 is '+values[i].toFixed(2)+' s — '+(values[i]>1?Math.round((values[i]-1)*100)+'% over budget.':Math.round((1-values[i])*100)+'% below budget.');}
$('chartLoad').oninput=e=>renderChart(Number(e.target.value));renderChart(4);
document.querySelectorAll('[data-desktop-width]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-desktop-width]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('desktopFrame').style.width=b.dataset.desktopWidth+'px';loadDesktop();});
let mobileDimension='load';
function mobileEvidence(){if(mobileDimension==='load'){$('mobileEvidenceTitle').textContent='A closer look at 40 calls.';$('mobileEvidenceBadge').textContent='1.18 s P95 · above budget';$('mobileEvidenceIntro').textContent="One representative slow turn. These stages add up to this turn's response time.";$('mobileEvidenceBody').innerHTML='<div class="cs-card" style="padding:16px;margin-top:20px"><h4>Turn timing</h4>'+[['Endpointing','224 ms'],['Model + tool wait','696 ms'],['Speech generation','260 ms'],['Total','1,180 ms']].map(([k,v])=>'<div style="display:flex;justify-content:space-between;gap:12px;padding:13px 0;border-bottom:1px solid var(--cs-border);font-size:14px"><span>'+k+'</span><span>'+v+'</span></div>').join('')+'</div><div class="chat-bubble"><small>CALLER</small>Can you check my refund?</div><div class="chat-bubble agent"><small>AGENT</small>Your refund has been approved.</div>';}else{$('mobileEvidenceTitle').textContent='The interruption changed the task.';$('mobileEvidenceBadge').textContent='Failed · corrected scope missed';$('mobileEvidenceIntro').textContent='An illustrative failed conversation from the interrupted-refund scenario.';$('mobileEvidenceBody').innerHTML='<div class="chat-bubble"><small>CALLER</small>Actually, I only want to refund one item.</div><div class="chat-bubble agent"><small>AGENT</small>I will refund the full order.</div><div class="phone-notice"><p>The agent did not adopt the caller’s corrected intent.</p></div>';}}
function mobileOverview(){const quality=mobileDimension==='quality';$('mobileQuestion').textContent=quality?'Which scenario needs work?':'Where does the budget break?';$('mobileValues').innerHTML=(quality?[['Standard refund','97.6%'],['Escalation','96.4%'],['Noisy caller','94.4%'],['Interrupted refund','88.4%']]:[['10 concurrent calls','0.63 s'],['20 concurrent calls','0.78 s'],['40 concurrent calls','1.18 s']]).map(([k,v])=>'<div style="display:flex;justify-content:space-between;gap:12px;font-size:14px;padding:14px 0;border-bottom:1px solid var(--cs-border)"><span>'+k+'</span><span>'+v+'</span></div>').join('');$('mobileTakeaway').textContent=quality?'Interrupted refunds have the lowest success. Start with their failed examples.':'Latency is within budget at 20 calls. The first tested breach is at 40.';mobileEvidence();}
keyboardTabs('.mobile-tab',b=>{mobileDimension=b.dataset.mobile;mobileOverview();});mobileOverview();
$('mobileOpenEvidence').onclick=()=>{$('evidencePhone').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});$('mobileBack').focus({preventScroll:true});};
$('mobileBack').onclick=()=>{$('mobileOpenEvidence').scrollIntoView({behavior:'auto',block:'center'});$('mobileOpenEvidence').focus({preventScroll:true});};
document.querySelectorAll('[data-mobile-nav]').forEach(b=>b.onclick=()=>{const overview=b.dataset.mobileNav==='overview';$('mobileOverview').hidden=!overview;$('mobileRuns').hidden=overview;document.querySelectorAll('[data-mobile-nav]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
document.querySelectorAll('[data-mobile-run]').forEach(b=>b.onclick=()=>{$('mobileRunStatus').textContent=b.dataset.mobileRun==='128'?'Run #128 · v2.4 · 94.2% success · 20 calls within latency budget.':'Run #127 · v2.3 · 91.8% success · 40 calls at the latency limit.';});
const tokenRows=[];
function flatten(obj,path){Object.entries(obj).forEach(([k,v])=>{const key=path?path+'.'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v))flatten(v,key);else tokenRows.push({key,group:key.split('.')[0],value:Array.isArray(v)?v.join(', '):String(v)});});}
for(const group of ['color','space','radius','size','typography','motion','layout'])flatten(DATA.tokens[group],group);
function renderTokens(){const query=$('tokenSearch').value.trim().toLowerCase(),group=$('tokenGroup').value;const filtered=tokenRows.filter(r=>(group==='all'||r.group===group)&&(!query||(r.key+' '+r.value).toLowerCase().includes(query)));$('tokenCount').textContent=filtered.length+' of '+tokenRows.length+' token values';$('tokenTable').innerHTML=filtered.length?'<div class="table-wrap"><table class="data-table"><thead><tr><th>Token</th><th>Value</th><th>Copy</th></tr></thead><tbody>'+filtered.map(r=>'<tr><td><code>'+esc(r.key)+'</code></td><td>'+(/^#[0-9a-f]{6}$/i.test(r.value)?'<i style="display:inline-block;width:15px;height:15px;vertical-align:middle;margin-right:8px;border:1px solid #0002;border-radius:3px;background:'+r.value+'"></i>':'')+'<code>'+esc(r.value)+'</code></td><td><button class="cs-button cs-button-text token-copy" data-value="'+esc(r.value)+'" aria-label="Copy '+esc(r.key)+'">Copy</button></td></tr>').join('')+'</tbody></table></div>':'<div class="state-demo"><strong>No matching tokens.</strong><p>Try a color role, radius, or spacing value.</p></div>';$('tokenTable').querySelectorAll('.token-copy').forEach(b=>b.onclick=()=>copyText(b.dataset.value));}
$('tokenSearch').oninput=renderTokens;$('tokenGroup').onchange=renderTokens;renderTokens();
$('resourceSelect').innerHTML=Object.keys(DATA.resources).map(name=>'<option value="'+esc(name)+'">'+esc(name)+'</option>').join('');
function updateResource(){$('resourceCode').textContent=DATA.resources[$('resourceSelect').value];}
$('resourceSelect').onchange=updateResource;updateResource();$('copyResource').onclick=()=>copyText(DATA.resources[$('resourceSelect').value]);$('downloadResource').onclick=()=>download($('resourceSelect').value);$('inlinePrompt').textContent=DATA.resources['APPLY_STYLE_PROMPT.md'];
selectSection(location.hash.slice(1)||'overview',false);
